package JdbcExercise;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class JdbcAffairs {
    public static void main(String[] args) {
        Connection connection=null;
        try {
            connection = JdbcUtils.getConnection();
            //开启事务
            connection.setAutoCommit(false);
            String sql1="update account set money= money-? where name=?";
            String sql2="update account set money= money+? where name=?";
            PreparedStatement preparedStatement1 = connection.prepareStatement(sql1);
            PreparedStatement preparedStatement2 = connection.prepareStatement(sql2);
            preparedStatement1.setInt(1,500);
            preparedStatement1.setString(2,"a");
            preparedStatement2.setInt(1,500);
            preparedStatement2.setString(2,"b");
            preparedStatement1.executeUpdate();
            //手动制造异常
            int i=3/0;
            preparedStatement2.executeUpdate();
            //提交事务
            connection.commit();
            JdbcUtils.close(preparedStatement1,connection);
            JdbcUtils.close(preparedStatement2,null);
        } catch (Exception e) {
            //如果出现任何异常要用catch语句抓，所以回滚操作放在catch;同时应注意异常的抓应该为大的Exception
            try {
                connection.rollback();
            } catch (SQLException e1) {
                e1.printStackTrace();
            }
            e.printStackTrace();
        }
    }
}
